"""created entity

Revision ID: d057ae9ccdb1
Revises: 
Create Date: 2023-11-02 22:05:32.932883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd057ae9ccdb1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question1', sa.String(length=100), nullable=True),
    sa.Column('question2', sa.String(length=100), nullable=True),
    sa.Column('question3', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    # ### end Alembic commands ###
